### ISSUE TITLE
why not 9020 sff?

### ISSUE THREAD

**Issue by asheenlevrai** [HarbinRepairs/Dell-Optiplex-MB-Header-Adapters#1]
Hi :)

Why won't the front panel adapter kit work with 9020 sff (and usff)?

Is there any chance you will make an adapter that is compatible with the 9020 sff?

Thank you very much in advance.
Best,
-a-

**Comment by HarbinRepairs** [comment]
The current motherboard adapter (DFP19-T) will not work with SFF due to the connector being in a different area that is constrained and/or it might have a different connector than the MT variant. We plan to make adapters for the SFF models in the future.
