### ISSUE TITLE
Dell power adapter

### ISSUE THREAD

**Issue by Capnklayton** [HarbinRepairs/Dell-Optiplex-MB-Header-Adapters#2]
I’m using the power adapter for optiplex 990 and running into the post power error at the beginning. I should work for 990 right it looks like the front panel adapter is working flawlessly.

**Comment by HarbinRepairs** [comment]
If you are referring to the power button adapter (DFP05-PWR-T) then that adapter alone will not resolve the front panel I/O error, you also must have the DFP34-T adapter installed for the front panel I/O error to clear. If this is an SFF model then unfortunately we don't have an adapter for that model as of right now.

**Comment by Capnklayton** [comment]
I figured it out. Turned the adapter opposite the white line where the arrow matches the missing pin.

**Comment by Capnklayton** [comment]
![image](https://user-images.githubusercontent.com/88681803/128764811-e5ceffb9-028e-4ab7-a32f-4bab4f900f9e.jpg)heres a photo
